import 'package:injectable/injectable.dart';

import '../../task/domain/models/task.dart';
import '../data/ai_client.dart';
import '../data/ai_prefs.dart';
import 'ai_prompt_builder.dart';
import 'ai_target.dart';

abstract class AiRepository {
  /// Whether an AI API key is configured for this build.
  bool get isConfigured;

  /// The last-selected target platform (cached globally; defaults to Claude).
  AiTarget getTarget();

  /// Persists [target] as the new last-selected default.
  Future<void> setTarget(AiTarget target);

  /// The cached detected framework/stack, or null if not detected yet.
  String? getFramework();

  /// Caches [framework] as the detected project stack.
  Future<void> cacheFramework(String framework);

  /// Forgets the cached framework so the next generation re-detects it.
  Future<void> clearFramework();

  /// Streams a fix prompt tailored for [target], generated by the model from
  /// [task]'s linked Zentao bug. When no framework is cached the model emits a
  /// leading `FRAMEWORK: <name>` marker line (see [aiFrameworkMarker]) for the
  /// caller to cache and strip.
  Stream<String> generatePrompt(Task task, AiTarget target);
}

@LazySingleton(as: AiRepository)
class AiRepositoryImpl implements AiRepository {
  AiRepositoryImpl(this._client, this._prefs);

  final AiClient _client;
  final AiPrefs _prefs;

  @override
  bool get isConfigured => _client.isConfigured;

  @override
  AiTarget getTarget() => _prefs.getTarget();

  @override
  Future<void> setTarget(AiTarget target) => _prefs.setTarget(target);

  @override
  String? getFramework() => _prefs.getFramework();

  @override
  Future<void> cacheFramework(String framework) =>
      _prefs.setFramework(framework);

  @override
  Future<void> clearFramework() => _prefs.clearFramework();

  @override
  Stream<String> generatePrompt(Task task, AiTarget target) {
    final prompt = buildAiPromptRequest(
      task,
      target,
      cachedFramework: _prefs.getFramework(),
    );
    // Prompt generation is text-only — no image attachments are sent.
    return _client.resolveBug(prompt: prompt, images: const []);
  }
}
