// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../database/attendance/attendance_entity.dart';
import '../database/checkout_reminder/checkout_reminder_settings_entity.dart';
import '../database/leave_reminder/commute_sample_entity.dart';
import '../database/leave_reminder/leave_reminder_settings_entity.dart';
import '../database/leave_reminder/notification_log_entity.dart';
import '../database/location_log/location_log_entity.dart';
import '../database/location_log/location_log_settings_entity.dart';
import '../database/task/task_entity.dart';
import '../database/task/task_time_log_entity.dart';
import '../database/work_schedule/work_schedule_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3634202302063934173),
    name: 'AttendanceEntity',
    lastPropertyId: const obx_int.IdUid(17, 6172843247117442083),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3812493402895089283),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6533698415135498462),
        name: 'workDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 827718280199297048),
        name: 'dayKey',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 761515154906713108),
        name: 'checkIn',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8613248500409985893),
        name: 'checkOut',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5831982607944423215),
        name: 'expectedStartMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1037286667621152561),
        name: 'expectedEndMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1652360811631904003),
        name: 'lunchMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9179913853188163101),
        name: 'workedMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8882244345145863238),
        name: 'lateMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5238704339051076552),
        name: 'overtimeMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 104789441039393961),
        name: 'earlyLeaveMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3206949071363524572),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8812442125162009907),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7088261182752015497),
        name: 'isEdited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1412025691473653403),
        name: 'editedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6172843247117442083),
        name: 'expectedLunchStartMinute',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2238911637897544245),
    name: 'WorkScheduleEntity',
    lastPropertyId: const obx_int.IdUid(7, 5878804006344107488),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7907798419581364564),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3930892267700988915),
        name: 'startMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 766713613177109274),
        name: 'endMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6715395547933767171),
        name: 'lunchMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8786391382863949686),
        name: 'reminderMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3290344717990253593),
        name: 'workingDaysMask',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5878804006344107488),
        name: 'lunchStartMinute',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6679202978330319836),
    name: 'LeaveReminderSettingsEntity',
    lastPropertyId: const obx_int.IdUid(13, 2119001519333355787),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8643290920413546602),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6380066240319687841),
        name: 'enabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8441424190231141368),
        name: 'homeLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2029207749746645957),
        name: 'homeLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7192263263464208526),
        name: 'workLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 445201863530615467),
        name: 'workLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8333041636312710540),
        name: 'lastCommuteMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2800194175799672012),
        name: 'lastCommuteUpdatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2573635761723676714),
        name: 'headsUpLeadMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7888588477064653157),
        name: 'homeAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5581931614869045293),
        name: 'workAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4560392765351613816),
        name: 'waypointsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2119001519333355787),
        name: 'workRadiusMeters',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5221361258848994198),
    name: 'CheckoutReminderSettingsEntity',
    lastPropertyId: const obx_int.IdUid(3, 7666057814368555657),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1389034202621098215),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4853571702626953403),
        name: 'enabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7666057814368555657),
        name: 'leadMinutes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7143482092043233428),
    name: 'CommuteSampleEntity',
    lastPropertyId: const obx_int.IdUid(3, 9115101797300401571),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6200563535257375930),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7717060570291755860),
        name: 'minutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9115101797300401571),
        name: 'capturedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4635867025159930616),
    name: 'NotificationLogEntity',
    lastPropertyId: const obx_int.IdUid(5, 6911550269401460243),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9204796880613570877),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2121627296322521568),
        name: 'notificationId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1663780830057021966),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 805734213067342852),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6911550269401460243),
        name: 'scheduledAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2824549352060330144),
    name: 'LocationLogEntity',
    lastPropertyId: const obx_int.IdUid(7, 532066523535157237),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6063035504128070621),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4518036191976760167),
        name: 'dayKey',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8070911131300955897),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4741423178368908379),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5530196140578984042),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2814586780108219468),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 532066523535157237),
        name: 'address',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 9063259141520829508),
    name: 'LocationLogSettingsEntity',
    lastPropertyId: const obx_int.IdUid(2, 2934555230439234096),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2730982632818323062),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2934555230439234096),
        name: 'enabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 6191964457532316515),
    name: 'TaskEntity',
    lastPropertyId: const obx_int.IdUid(22, 8201534001140874554),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2281164033161657957),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2968911545761269172),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2115774712449689747),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4577447944555243224),
        name: 'done',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 875205466672412041),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1799410581777712473),
        name: 'zentaoTaskId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3058599899231211393),
        name: 'zentaoStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7768630553333512898),
        name: 'zentaoLastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4491951567801882255),
        name: 'elapsedSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1274764557099511359),
        name: 'timerStartedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7311600913338381351),
        name: 'zentaoBugId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7583442905243618321),
        name: 'zentaoPriority',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 16665288937463160),
        name: 'zentaoSeverity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8159886837718871165),
        name: 'zentaoProductId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5475659252933608524),
        name: 'zentaoProductName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8455426037410360777),
        name: 'zentaoProductPriority',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6518626843692918939),
        name: 'priority',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2406249912600057726),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 375707130230014140),
        name: 'zentaoAttachmentsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4510822663679732228),
        name: 'zentaoDetailSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1744186708702947320),
        name: 'zentaoConfirmed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 8201534001140874554),
        name: 'zentaoOpenedBy',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 8169882491915754974),
    name: 'TaskTimeLogEntity',
    lastPropertyId: const obx_int.IdUid(4, 2034381477115506792),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3700414153851590729),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4067976295464410389),
        name: 'taskId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2316015121435908552),
        name: 'day',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2034381477115506792),
        name: 'seconds',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 8169882491915754974),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AttendanceEntity: obx_int.EntityDefinition<AttendanceEntity>(
      model: _entities[0],
      toOneRelations: (AttendanceEntity object) => [],
      toManyRelations: (AttendanceEntity object) => {},
      getId: (AttendanceEntity object) => object.id,
      setId: (AttendanceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AttendanceEntity object, fb.Builder fbb) {
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.workDate.millisecondsSinceEpoch);
        fbb.addInt64(2, object.dayKey);
        fbb.addInt64(3, object.checkIn?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.checkOut?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.expectedStartMinute);
        fbb.addInt64(6, object.expectedEndMinute);
        fbb.addInt64(7, object.lunchMinutes);
        fbb.addInt64(8, object.workedMinutes);
        fbb.addInt64(9, object.lateMinutes);
        fbb.addInt64(10, object.overtimeMinutes);
        fbb.addInt64(11, object.earlyLeaveMinutes);
        fbb.addInt64(12, object.status);
        fbb.addOffset(13, noteOffset);
        fbb.addBool(14, object.isEdited);
        fbb.addInt64(15, object.editedAt?.millisecondsSinceEpoch);
        fbb.addInt64(16, object.expectedLunchStartMinute);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final checkInValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final checkOutValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final editedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final workDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final dayKeyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final expectedStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final expectedEndMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final lunchMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final expectedLunchStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final workedMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final lateMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final overtimeMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final earlyLeaveMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final checkInParam = checkInValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkInValue);
        final checkOutParam = checkOutValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkOutValue);
        final isEditedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final editedAtParam = editedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(editedAtValue);
        final object = AttendanceEntity(
          workDate: workDateParam,
          dayKey: dayKeyParam,
          expectedStartMinute: expectedStartMinuteParam,
          expectedEndMinute: expectedEndMinuteParam,
          lunchMinutes: lunchMinutesParam,
          expectedLunchStartMinute: expectedLunchStartMinuteParam,
          workedMinutes: workedMinutesParam,
          lateMinutes: lateMinutesParam,
          overtimeMinutes: overtimeMinutesParam,
          earlyLeaveMinutes: earlyLeaveMinutesParam,
          status: statusParam,
          note: noteParam,
          checkIn: checkInParam,
          checkOut: checkOutParam,
          isEdited: isEditedParam,
          editedAt: editedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    WorkScheduleEntity: obx_int.EntityDefinition<WorkScheduleEntity>(
      model: _entities[1],
      toOneRelations: (WorkScheduleEntity object) => [],
      toManyRelations: (WorkScheduleEntity object) => {},
      getId: (WorkScheduleEntity object) => object.id,
      setId: (WorkScheduleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WorkScheduleEntity object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.startMinute);
        fbb.addInt64(2, object.endMinute);
        fbb.addInt64(3, object.lunchMinutes);
        fbb.addInt64(4, object.reminderMinutes);
        fbb.addInt64(5, object.workingDaysMask);
        fbb.addInt64(6, object.lunchStartMinute);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final endMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lunchMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final lunchStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final reminderMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final workingDaysMaskParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = WorkScheduleEntity(
          startMinute: startMinuteParam,
          endMinute: endMinuteParam,
          lunchMinutes: lunchMinutesParam,
          lunchStartMinute: lunchStartMinuteParam,
          reminderMinutes: reminderMinutesParam,
          workingDaysMask: workingDaysMaskParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LeaveReminderSettingsEntity:
        obx_int.EntityDefinition<LeaveReminderSettingsEntity>(
          model: _entities[2],
          toOneRelations: (LeaveReminderSettingsEntity object) => [],
          toManyRelations: (LeaveReminderSettingsEntity object) => {},
          getId: (LeaveReminderSettingsEntity object) => object.id,
          setId: (LeaveReminderSettingsEntity object, int id) {
            object.id = id;
          },
          objectToFB: (LeaveReminderSettingsEntity object, fb.Builder fbb) {
            final homeAddressOffset = object.homeAddress == null
                ? null
                : fbb.writeString(object.homeAddress!);
            final workAddressOffset = object.workAddress == null
                ? null
                : fbb.writeString(object.workAddress!);
            final waypointsJsonOffset = object.waypointsJson == null
                ? null
                : fbb.writeString(object.waypointsJson!);
            fbb.startTable(14);
            fbb.addInt64(0, object.id);
            fbb.addBool(1, object.enabled);
            fbb.addFloat64(2, object.homeLat);
            fbb.addFloat64(3, object.homeLng);
            fbb.addFloat64(4, object.workLat);
            fbb.addFloat64(5, object.workLng);
            fbb.addInt64(6, object.lastCommuteMinutes);
            fbb.addInt64(
              7,
              object.lastCommuteUpdatedAt?.millisecondsSinceEpoch,
            );
            fbb.addInt64(8, object.headsUpLeadMinutes);
            fbb.addOffset(9, homeAddressOffset);
            fbb.addOffset(10, workAddressOffset);
            fbb.addOffset(11, waypointsJsonOffset);
            fbb.addInt64(12, object.workRadiusMeters);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final lastCommuteUpdatedAtValue = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 18);
            final enabledParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final homeLatParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              8,
            );
            final homeLngParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              10,
            );
            final homeAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 22);
            final workLatParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              12,
            );
            final workLngParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              14,
            );
            final workAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 24);
            final lastCommuteMinutesParam = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 16);
            final lastCommuteUpdatedAtParam = lastCommuteUpdatedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(
                    lastCommuteUpdatedAtValue,
                  );
            final headsUpLeadMinutesParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              20,
              0,
            );
            final waypointsJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 26);
            final workRadiusMetersParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              28,
              0,
            );
            final object = LeaveReminderSettingsEntity(
              enabled: enabledParam,
              homeLat: homeLatParam,
              homeLng: homeLngParam,
              homeAddress: homeAddressParam,
              workLat: workLatParam,
              workLng: workLngParam,
              workAddress: workAddressParam,
              lastCommuteMinutes: lastCommuteMinutesParam,
              lastCommuteUpdatedAt: lastCommuteUpdatedAtParam,
              headsUpLeadMinutes: headsUpLeadMinutesParam,
              waypointsJson: waypointsJsonParam,
              workRadiusMeters: workRadiusMetersParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    CheckoutReminderSettingsEntity:
        obx_int.EntityDefinition<CheckoutReminderSettingsEntity>(
          model: _entities[3],
          toOneRelations: (CheckoutReminderSettingsEntity object) => [],
          toManyRelations: (CheckoutReminderSettingsEntity object) => {},
          getId: (CheckoutReminderSettingsEntity object) => object.id,
          setId: (CheckoutReminderSettingsEntity object, int id) {
            object.id = id;
          },
          objectToFB: (CheckoutReminderSettingsEntity object, fb.Builder fbb) {
            fbb.startTable(4);
            fbb.addInt64(0, object.id);
            fbb.addBool(1, object.enabled);
            fbb.addInt64(2, object.leadMinutes);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final enabledParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final leadMinutesParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            final object = CheckoutReminderSettingsEntity(
              enabled: enabledParam,
              leadMinutes: leadMinutesParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    CommuteSampleEntity: obx_int.EntityDefinition<CommuteSampleEntity>(
      model: _entities[4],
      toOneRelations: (CommuteSampleEntity object) => [],
      toManyRelations: (CommuteSampleEntity object) => {},
      getId: (CommuteSampleEntity object) => object.id,
      setId: (CommuteSampleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CommuteSampleEntity object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.minutes);
        fbb.addInt64(2, object.capturedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final minutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final capturedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = CommuteSampleEntity(
          minutes: minutesParam,
          capturedAt: capturedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NotificationLogEntity: obx_int.EntityDefinition<NotificationLogEntity>(
      model: _entities[5],
      toOneRelations: (NotificationLogEntity object) => [],
      toManyRelations: (NotificationLogEntity object) => {},
      getId: (NotificationLogEntity object) => object.id,
      setId: (NotificationLogEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationLogEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.notificationId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, bodyOffset);
        fbb.addInt64(4, object.scheduledAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final notificationIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final scheduledAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = NotificationLogEntity(
          notificationId: notificationIdParam,
          title: titleParam,
          body: bodyParam,
          scheduledAt: scheduledAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LocationLogEntity: obx_int.EntityDefinition<LocationLogEntity>(
      model: _entities[6],
      toOneRelations: (LocationLogEntity object) => [],
      toManyRelations: (LocationLogEntity object) => {},
      getId: (LocationLogEntity object) => object.id,
      setId: (LocationLogEntity object, int id) {
        object.id = id;
      },
      objectToFB: (LocationLogEntity object, fb.Builder fbb) {
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.dayKey);
        fbb.addInt64(2, object.type);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addFloat64(4, object.latitude);
        fbb.addFloat64(5, object.longitude);
        fbb.addOffset(6, addressOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dayKeyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = LocationLogEntity(
          dayKey: dayKeyParam,
          type: typeParam,
          timestamp: timestampParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          address: addressParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LocationLogSettingsEntity:
        obx_int.EntityDefinition<LocationLogSettingsEntity>(
          model: _entities[7],
          toOneRelations: (LocationLogSettingsEntity object) => [],
          toManyRelations: (LocationLogSettingsEntity object) => {},
          getId: (LocationLogSettingsEntity object) => object.id,
          setId: (LocationLogSettingsEntity object, int id) {
            object.id = id;
          },
          objectToFB: (LocationLogSettingsEntity object, fb.Builder fbb) {
            fbb.startTable(3);
            fbb.addInt64(0, object.id);
            fbb.addBool(1, object.enabled);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final enabledParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final object = LocationLogSettingsEntity(enabled: enabledParam)
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
      model: _entities[8],
      toOneRelations: (TaskEntity object) => [],
      toManyRelations: (TaskEntity object) => {},
      getId: (TaskEntity object) => object.id,
      setId: (TaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TaskEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final zentaoStatusOffset = object.zentaoStatus == null
            ? null
            : fbb.writeString(object.zentaoStatus!);
        final zentaoProductNameOffset = object.zentaoProductName == null
            ? null
            : fbb.writeString(object.zentaoProductName!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final zentaoAttachmentsJsonOffset = object.zentaoAttachmentsJson == null
            ? null
            : fbb.writeString(object.zentaoAttachmentsJson!);
        final zentaoOpenedByOffset = object.zentaoOpenedBy == null
            ? null
            : fbb.writeString(object.zentaoOpenedBy!);
        fbb.startTable(23);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.done);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.zentaoTaskId);
        fbb.addOffset(6, zentaoStatusOffset);
        fbb.addInt64(7, object.zentaoLastSyncedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.elapsedSeconds);
        fbb.addInt64(9, object.timerStartedAt?.millisecondsSinceEpoch);
        fbb.addInt64(10, object.zentaoBugId);
        fbb.addInt64(11, object.zentaoPriority);
        fbb.addInt64(12, object.zentaoSeverity);
        fbb.addInt64(13, object.zentaoProductId);
        fbb.addOffset(14, zentaoProductNameOffset);
        fbb.addInt64(15, object.zentaoProductPriority);
        fbb.addInt64(16, object.priority);
        fbb.addOffset(17, notesOffset);
        fbb.addOffset(18, zentaoAttachmentsJsonOffset);
        fbb.addInt64(19, object.zentaoDetailSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(20, object.zentaoConfirmed);
        fbb.addOffset(21, zentaoOpenedByOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final zentaoLastSyncedAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final timerStartedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final zentaoDetailSyncedAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final doneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final zentaoTaskIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final zentaoBugIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final zentaoStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final priorityParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final zentaoAttachmentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final zentaoPriorityParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final zentaoSeverityParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final zentaoProductIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final zentaoProductNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final zentaoProductPriorityParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 34);
        final zentaoLastSyncedAtParam = zentaoLastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(zentaoLastSyncedAtValue);
        final zentaoDetailSyncedAtParam = zentaoDetailSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(zentaoDetailSyncedAtValue);
        final elapsedSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final timerStartedAtParam = timerStartedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(timerStartedAtValue);
        final zentaoConfirmedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          44,
          false,
        );
        final zentaoOpenedByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final object = TaskEntity(
          title: titleParam,
          description: descriptionParam,
          done: doneParam,
          createdAt: createdAtParam,
          zentaoTaskId: zentaoTaskIdParam,
          zentaoBugId: zentaoBugIdParam,
          zentaoStatus: zentaoStatusParam,
          priority: priorityParam,
          notes: notesParam,
          zentaoAttachmentsJson: zentaoAttachmentsJsonParam,
          zentaoPriority: zentaoPriorityParam,
          zentaoSeverity: zentaoSeverityParam,
          zentaoProductId: zentaoProductIdParam,
          zentaoProductName: zentaoProductNameParam,
          zentaoProductPriority: zentaoProductPriorityParam,
          zentaoLastSyncedAt: zentaoLastSyncedAtParam,
          zentaoDetailSyncedAt: zentaoDetailSyncedAtParam,
          elapsedSeconds: elapsedSecondsParam,
          timerStartedAt: timerStartedAtParam,
          zentaoConfirmed: zentaoConfirmedParam,
          zentaoOpenedBy: zentaoOpenedByParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TaskTimeLogEntity: obx_int.EntityDefinition<TaskTimeLogEntity>(
      model: _entities[9],
      toOneRelations: (TaskTimeLogEntity object) => [],
      toManyRelations: (TaskTimeLogEntity object) => {},
      getId: (TaskTimeLogEntity object) => object.id,
      setId: (TaskTimeLogEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TaskTimeLogEntity object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.taskId);
        fbb.addInt64(2, object.day.millisecondsSinceEpoch);
        fbb.addInt64(3, object.seconds);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final taskIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dayParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final secondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = TaskTimeLogEntity(
          taskId: taskIdParam,
          day: dayParam,
          seconds: secondsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AttendanceEntity] entity fields to define ObjectBox queries.
class AttendanceEntity_ {
  /// See [AttendanceEntity.id].
  static final id = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[0],
  );

  /// See [AttendanceEntity.workDate].
  static final workDate = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[1],
  );

  /// See [AttendanceEntity.dayKey].
  static final dayKey = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[2],
  );

  /// See [AttendanceEntity.checkIn].
  static final checkIn = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[3],
  );

  /// See [AttendanceEntity.checkOut].
  static final checkOut = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[4],
  );

  /// See [AttendanceEntity.expectedStartMinute].
  static final expectedStartMinute = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[5],
  );

  /// See [AttendanceEntity.expectedEndMinute].
  static final expectedEndMinute = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[6],
  );

  /// See [AttendanceEntity.lunchMinutes].
  static final lunchMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[7],
  );

  /// See [AttendanceEntity.workedMinutes].
  static final workedMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[8],
  );

  /// See [AttendanceEntity.lateMinutes].
  static final lateMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[9],
  );

  /// See [AttendanceEntity.overtimeMinutes].
  static final overtimeMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[10],
  );

  /// See [AttendanceEntity.earlyLeaveMinutes].
  static final earlyLeaveMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[11],
  );

  /// See [AttendanceEntity.status].
  static final status = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[12],
  );

  /// See [AttendanceEntity.note].
  static final note = obx.QueryStringProperty<AttendanceEntity>(
    _entities[0].properties[13],
  );

  /// See [AttendanceEntity.isEdited].
  static final isEdited = obx.QueryBooleanProperty<AttendanceEntity>(
    _entities[0].properties[14],
  );

  /// See [AttendanceEntity.editedAt].
  static final editedAt = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[15],
  );

  /// See [AttendanceEntity.expectedLunchStartMinute].
  static final expectedLunchStartMinute =
      obx.QueryIntegerProperty<AttendanceEntity>(_entities[0].properties[16]);
}

/// [WorkScheduleEntity] entity fields to define ObjectBox queries.
class WorkScheduleEntity_ {
  /// See [WorkScheduleEntity.id].
  static final id = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[0],
  );

  /// See [WorkScheduleEntity.startMinute].
  static final startMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[1],
  );

  /// See [WorkScheduleEntity.endMinute].
  static final endMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[2],
  );

  /// See [WorkScheduleEntity.lunchMinutes].
  static final lunchMinutes = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[3],
  );

  /// See [WorkScheduleEntity.reminderMinutes].
  static final reminderMinutes = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[4],
  );

  /// See [WorkScheduleEntity.workingDaysMask].
  static final workingDaysMask = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[5],
  );

  /// See [WorkScheduleEntity.lunchStartMinute].
  static final lunchStartMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[6],
  );
}

/// [LeaveReminderSettingsEntity] entity fields to define ObjectBox queries.
class LeaveReminderSettingsEntity_ {
  /// See [LeaveReminderSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[0],
  );

  /// See [LeaveReminderSettingsEntity.enabled].
  static final enabled = obx.QueryBooleanProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[1],
  );

  /// See [LeaveReminderSettingsEntity.homeLat].
  static final homeLat = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[2],
  );

  /// See [LeaveReminderSettingsEntity.homeLng].
  static final homeLng = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[3],
  );

  /// See [LeaveReminderSettingsEntity.workLat].
  static final workLat = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[4],
  );

  /// See [LeaveReminderSettingsEntity.workLng].
  static final workLng = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[5],
  );

  /// See [LeaveReminderSettingsEntity.lastCommuteMinutes].
  static final lastCommuteMinutes =
      obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[6],
      );

  /// See [LeaveReminderSettingsEntity.lastCommuteUpdatedAt].
  static final lastCommuteUpdatedAt =
      obx.QueryDateProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[7],
      );

  /// See [LeaveReminderSettingsEntity.headsUpLeadMinutes].
  static final headsUpLeadMinutes =
      obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[8],
      );

  /// See [LeaveReminderSettingsEntity.homeAddress].
  static final homeAddress =
      obx.QueryStringProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[9],
      );

  /// See [LeaveReminderSettingsEntity.workAddress].
  static final workAddress =
      obx.QueryStringProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[10],
      );

  /// See [LeaveReminderSettingsEntity.waypointsJson].
  static final waypointsJson =
      obx.QueryStringProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[11],
      );

  /// See [LeaveReminderSettingsEntity.workRadiusMeters].
  static final workRadiusMeters =
      obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[12],
      );
}

/// [CheckoutReminderSettingsEntity] entity fields to define ObjectBox queries.
class CheckoutReminderSettingsEntity_ {
  /// See [CheckoutReminderSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<CheckoutReminderSettingsEntity>(
    _entities[3].properties[0],
  );

  /// See [CheckoutReminderSettingsEntity.enabled].
  static final enabled =
      obx.QueryBooleanProperty<CheckoutReminderSettingsEntity>(
        _entities[3].properties[1],
      );

  /// See [CheckoutReminderSettingsEntity.leadMinutes].
  static final leadMinutes =
      obx.QueryIntegerProperty<CheckoutReminderSettingsEntity>(
        _entities[3].properties[2],
      );
}

/// [CommuteSampleEntity] entity fields to define ObjectBox queries.
class CommuteSampleEntity_ {
  /// See [CommuteSampleEntity.id].
  static final id = obx.QueryIntegerProperty<CommuteSampleEntity>(
    _entities[4].properties[0],
  );

  /// See [CommuteSampleEntity.minutes].
  static final minutes = obx.QueryIntegerProperty<CommuteSampleEntity>(
    _entities[4].properties[1],
  );

  /// See [CommuteSampleEntity.capturedAt].
  static final capturedAt = obx.QueryDateProperty<CommuteSampleEntity>(
    _entities[4].properties[2],
  );
}

/// [NotificationLogEntity] entity fields to define ObjectBox queries.
class NotificationLogEntity_ {
  /// See [NotificationLogEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationLogEntity>(
    _entities[5].properties[0],
  );

  /// See [NotificationLogEntity.notificationId].
  static final notificationId = obx.QueryIntegerProperty<NotificationLogEntity>(
    _entities[5].properties[1],
  );

  /// See [NotificationLogEntity.title].
  static final title = obx.QueryStringProperty<NotificationLogEntity>(
    _entities[5].properties[2],
  );

  /// See [NotificationLogEntity.body].
  static final body = obx.QueryStringProperty<NotificationLogEntity>(
    _entities[5].properties[3],
  );

  /// See [NotificationLogEntity.scheduledAt].
  static final scheduledAt = obx.QueryDateProperty<NotificationLogEntity>(
    _entities[5].properties[4],
  );
}

/// [LocationLogEntity] entity fields to define ObjectBox queries.
class LocationLogEntity_ {
  /// See [LocationLogEntity.id].
  static final id = obx.QueryIntegerProperty<LocationLogEntity>(
    _entities[6].properties[0],
  );

  /// See [LocationLogEntity.dayKey].
  static final dayKey = obx.QueryIntegerProperty<LocationLogEntity>(
    _entities[6].properties[1],
  );

  /// See [LocationLogEntity.type].
  static final type = obx.QueryIntegerProperty<LocationLogEntity>(
    _entities[6].properties[2],
  );

  /// See [LocationLogEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<LocationLogEntity>(
    _entities[6].properties[3],
  );

  /// See [LocationLogEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<LocationLogEntity>(
    _entities[6].properties[4],
  );

  /// See [LocationLogEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<LocationLogEntity>(
    _entities[6].properties[5],
  );

  /// See [LocationLogEntity.address].
  static final address = obx.QueryStringProperty<LocationLogEntity>(
    _entities[6].properties[6],
  );
}

/// [LocationLogSettingsEntity] entity fields to define ObjectBox queries.
class LocationLogSettingsEntity_ {
  /// See [LocationLogSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<LocationLogSettingsEntity>(
    _entities[7].properties[0],
  );

  /// See [LocationLogSettingsEntity.enabled].
  static final enabled = obx.QueryBooleanProperty<LocationLogSettingsEntity>(
    _entities[7].properties[1],
  );
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.id].
  static final id = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[0],
  );

  /// See [TaskEntity.title].
  static final title = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[1],
  );

  /// See [TaskEntity.description].
  static final description = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[2],
  );

  /// See [TaskEntity.done].
  static final done = obx.QueryBooleanProperty<TaskEntity>(
    _entities[8].properties[3],
  );

  /// See [TaskEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[4],
  );

  /// See [TaskEntity.zentaoTaskId].
  static final zentaoTaskId = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[5],
  );

  /// See [TaskEntity.zentaoStatus].
  static final zentaoStatus = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[6],
  );

  /// See [TaskEntity.zentaoLastSyncedAt].
  static final zentaoLastSyncedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[7],
  );

  /// See [TaskEntity.elapsedSeconds].
  static final elapsedSeconds = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[8],
  );

  /// See [TaskEntity.timerStartedAt].
  static final timerStartedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[9],
  );

  /// See [TaskEntity.zentaoBugId].
  static final zentaoBugId = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[10],
  );

  /// See [TaskEntity.zentaoPriority].
  static final zentaoPriority = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[11],
  );

  /// See [TaskEntity.zentaoSeverity].
  static final zentaoSeverity = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[12],
  );

  /// See [TaskEntity.zentaoProductId].
  static final zentaoProductId = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[13],
  );

  /// See [TaskEntity.zentaoProductName].
  static final zentaoProductName = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[14],
  );

  /// See [TaskEntity.zentaoProductPriority].
  static final zentaoProductPriority = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[15],
  );

  /// See [TaskEntity.priority].
  static final priority = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[16],
  );

  /// See [TaskEntity.notes].
  static final notes = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[17],
  );

  /// See [TaskEntity.zentaoAttachmentsJson].
  static final zentaoAttachmentsJson = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[18],
  );

  /// See [TaskEntity.zentaoDetailSyncedAt].
  static final zentaoDetailSyncedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[19],
  );

  /// See [TaskEntity.zentaoConfirmed].
  static final zentaoConfirmed = obx.QueryBooleanProperty<TaskEntity>(
    _entities[8].properties[20],
  );

  /// See [TaskEntity.zentaoOpenedBy].
  static final zentaoOpenedBy = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[21],
  );
}

/// [TaskTimeLogEntity] entity fields to define ObjectBox queries.
class TaskTimeLogEntity_ {
  /// See [TaskTimeLogEntity.id].
  static final id = obx.QueryIntegerProperty<TaskTimeLogEntity>(
    _entities[9].properties[0],
  );

  /// See [TaskTimeLogEntity.taskId].
  static final taskId = obx.QueryIntegerProperty<TaskTimeLogEntity>(
    _entities[9].properties[1],
  );

  /// See [TaskTimeLogEntity.day].
  static final day = obx.QueryDateProperty<TaskTimeLogEntity>(
    _entities[9].properties[2],
  );

  /// See [TaskTimeLogEntity.seconds].
  static final seconds = obx.QueryIntegerProperty<TaskTimeLogEntity>(
    _entities[9].properties[3],
  );
}
