// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../database/attendance/attendance_entity.dart';
import '../database/checkout_reminder/checkout_reminder_settings_entity.dart';
import '../database/leave_reminder/leave_reminder_settings_entity.dart';
import '../database/work_schedule/work_schedule_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3634202302063934173),
    name: 'AttendanceEntity',
    lastPropertyId: const obx_int.IdUid(17, 6172843247117442083),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3812493402895089283),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6533698415135498462),
        name: 'workDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 827718280199297048),
        name: 'dayKey',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 761515154906713108),
        name: 'checkIn',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8613248500409985893),
        name: 'checkOut',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5831982607944423215),
        name: 'expectedStartMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1037286667621152561),
        name: 'expectedEndMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1652360811631904003),
        name: 'lunchMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9179913853188163101),
        name: 'workedMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8882244345145863238),
        name: 'lateMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5238704339051076552),
        name: 'overtimeMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 104789441039393961),
        name: 'earlyLeaveMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3206949071363524572),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8812442125162009907),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7088261182752015497),
        name: 'isEdited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1412025691473653403),
        name: 'editedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6172843247117442083),
        name: 'expectedLunchStartMinute',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2238911637897544245),
    name: 'WorkScheduleEntity',
    lastPropertyId: const obx_int.IdUid(7, 5878804006344107488),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7907798419581364564),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3930892267700988915),
        name: 'startMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 766713613177109274),
        name: 'endMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6715395547933767171),
        name: 'lunchMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8786391382863949686),
        name: 'reminderMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3290344717990253593),
        name: 'workingDaysMask',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5878804006344107488),
        name: 'lunchStartMinute',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6679202978330319836),
    name: 'LeaveReminderSettingsEntity',
    lastPropertyId: const obx_int.IdUid(9, 2573635761723676714),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8643290920413546602),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6380066240319687841),
        name: 'enabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8441424190231141368),
        name: 'homeLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2029207749746645957),
        name: 'homeLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7192263263464208526),
        name: 'workLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 445201863530615467),
        name: 'workLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8333041636312710540),
        name: 'lastCommuteMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2800194175799672012),
        name: 'lastCommuteUpdatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2573635761723676714),
        name: 'headsUpLeadMinutes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5221361258848994198),
    name: 'CheckoutReminderSettingsEntity',
    lastPropertyId: const obx_int.IdUid(3, 7666057814368555657),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1389034202621098215),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4853571702626953403),
        name: 'enabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7666057814368555657),
        name: 'leadMinutes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5221361258848994198),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AttendanceEntity: obx_int.EntityDefinition<AttendanceEntity>(
      model: _entities[0],
      toOneRelations: (AttendanceEntity object) => [],
      toManyRelations: (AttendanceEntity object) => {},
      getId: (AttendanceEntity object) => object.id,
      setId: (AttendanceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AttendanceEntity object, fb.Builder fbb) {
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.workDate.millisecondsSinceEpoch);
        fbb.addInt64(2, object.dayKey);
        fbb.addInt64(3, object.checkIn?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.checkOut?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.expectedStartMinute);
        fbb.addInt64(6, object.expectedEndMinute);
        fbb.addInt64(7, object.lunchMinutes);
        fbb.addInt64(8, object.workedMinutes);
        fbb.addInt64(9, object.lateMinutes);
        fbb.addInt64(10, object.overtimeMinutes);
        fbb.addInt64(11, object.earlyLeaveMinutes);
        fbb.addInt64(12, object.status);
        fbb.addOffset(13, noteOffset);
        fbb.addBool(14, object.isEdited);
        fbb.addInt64(15, object.editedAt?.millisecondsSinceEpoch);
        fbb.addInt64(16, object.expectedLunchStartMinute);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final checkInValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final checkOutValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final editedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final workDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final dayKeyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final expectedStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final expectedEndMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final lunchMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final expectedLunchStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final workedMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final lateMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final overtimeMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final earlyLeaveMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final checkInParam = checkInValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkInValue);
        final checkOutParam = checkOutValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(checkOutValue);
        final isEditedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final editedAtParam = editedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(editedAtValue);
        final object = AttendanceEntity(
          workDate: workDateParam,
          dayKey: dayKeyParam,
          expectedStartMinute: expectedStartMinuteParam,
          expectedEndMinute: expectedEndMinuteParam,
          lunchMinutes: lunchMinutesParam,
          expectedLunchStartMinute: expectedLunchStartMinuteParam,
          workedMinutes: workedMinutesParam,
          lateMinutes: lateMinutesParam,
          overtimeMinutes: overtimeMinutesParam,
          earlyLeaveMinutes: earlyLeaveMinutesParam,
          status: statusParam,
          note: noteParam,
          checkIn: checkInParam,
          checkOut: checkOutParam,
          isEdited: isEditedParam,
          editedAt: editedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    WorkScheduleEntity: obx_int.EntityDefinition<WorkScheduleEntity>(
      model: _entities[1],
      toOneRelations: (WorkScheduleEntity object) => [],
      toManyRelations: (WorkScheduleEntity object) => {},
      getId: (WorkScheduleEntity object) => object.id,
      setId: (WorkScheduleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WorkScheduleEntity object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.startMinute);
        fbb.addInt64(2, object.endMinute);
        fbb.addInt64(3, object.lunchMinutes);
        fbb.addInt64(4, object.reminderMinutes);
        fbb.addInt64(5, object.workingDaysMask);
        fbb.addInt64(6, object.lunchStartMinute);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final endMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lunchMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final lunchStartMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final reminderMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final workingDaysMaskParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = WorkScheduleEntity(
          startMinute: startMinuteParam,
          endMinute: endMinuteParam,
          lunchMinutes: lunchMinutesParam,
          lunchStartMinute: lunchStartMinuteParam,
          reminderMinutes: reminderMinutesParam,
          workingDaysMask: workingDaysMaskParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LeaveReminderSettingsEntity:
        obx_int.EntityDefinition<LeaveReminderSettingsEntity>(
          model: _entities[2],
          toOneRelations: (LeaveReminderSettingsEntity object) => [],
          toManyRelations: (LeaveReminderSettingsEntity object) => {},
          getId: (LeaveReminderSettingsEntity object) => object.id,
          setId: (LeaveReminderSettingsEntity object, int id) {
            object.id = id;
          },
          objectToFB: (LeaveReminderSettingsEntity object, fb.Builder fbb) {
            fbb.startTable(10);
            fbb.addInt64(0, object.id);
            fbb.addBool(1, object.enabled);
            fbb.addFloat64(2, object.homeLat);
            fbb.addFloat64(3, object.homeLng);
            fbb.addFloat64(4, object.workLat);
            fbb.addFloat64(5, object.workLng);
            fbb.addInt64(6, object.lastCommuteMinutes);
            fbb.addInt64(
              7,
              object.lastCommuteUpdatedAt?.millisecondsSinceEpoch,
            );
            fbb.addInt64(8, object.headsUpLeadMinutes);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final lastCommuteUpdatedAtValue = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 18);
            final enabledParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final homeLatParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              8,
            );
            final homeLngParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              10,
            );
            final workLatParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              12,
            );
            final workLngParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              14,
            );
            final lastCommuteMinutesParam = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 16);
            final lastCommuteUpdatedAtParam = lastCommuteUpdatedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(
                    lastCommuteUpdatedAtValue,
                  );
            final headsUpLeadMinutesParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              20,
              0,
            );
            final object = LeaveReminderSettingsEntity(
              enabled: enabledParam,
              homeLat: homeLatParam,
              homeLng: homeLngParam,
              workLat: workLatParam,
              workLng: workLngParam,
              lastCommuteMinutes: lastCommuteMinutesParam,
              lastCommuteUpdatedAt: lastCommuteUpdatedAtParam,
              headsUpLeadMinutes: headsUpLeadMinutesParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    CheckoutReminderSettingsEntity:
        obx_int.EntityDefinition<CheckoutReminderSettingsEntity>(
          model: _entities[3],
          toOneRelations: (CheckoutReminderSettingsEntity object) => [],
          toManyRelations: (CheckoutReminderSettingsEntity object) => {},
          getId: (CheckoutReminderSettingsEntity object) => object.id,
          setId: (CheckoutReminderSettingsEntity object, int id) {
            object.id = id;
          },
          objectToFB: (CheckoutReminderSettingsEntity object, fb.Builder fbb) {
            fbb.startTable(4);
            fbb.addInt64(0, object.id);
            fbb.addBool(1, object.enabled);
            fbb.addInt64(2, object.leadMinutes);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final enabledParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final leadMinutesParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            final object = CheckoutReminderSettingsEntity(
              enabled: enabledParam,
              leadMinutes: leadMinutesParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AttendanceEntity] entity fields to define ObjectBox queries.
class AttendanceEntity_ {
  /// See [AttendanceEntity.id].
  static final id = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[0],
  );

  /// See [AttendanceEntity.workDate].
  static final workDate = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[1],
  );

  /// See [AttendanceEntity.dayKey].
  static final dayKey = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[2],
  );

  /// See [AttendanceEntity.checkIn].
  static final checkIn = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[3],
  );

  /// See [AttendanceEntity.checkOut].
  static final checkOut = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[4],
  );

  /// See [AttendanceEntity.expectedStartMinute].
  static final expectedStartMinute = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[5],
  );

  /// See [AttendanceEntity.expectedEndMinute].
  static final expectedEndMinute = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[6],
  );

  /// See [AttendanceEntity.lunchMinutes].
  static final lunchMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[7],
  );

  /// See [AttendanceEntity.workedMinutes].
  static final workedMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[8],
  );

  /// See [AttendanceEntity.lateMinutes].
  static final lateMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[9],
  );

  /// See [AttendanceEntity.overtimeMinutes].
  static final overtimeMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[10],
  );

  /// See [AttendanceEntity.earlyLeaveMinutes].
  static final earlyLeaveMinutes = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[11],
  );

  /// See [AttendanceEntity.status].
  static final status = obx.QueryIntegerProperty<AttendanceEntity>(
    _entities[0].properties[12],
  );

  /// See [AttendanceEntity.note].
  static final note = obx.QueryStringProperty<AttendanceEntity>(
    _entities[0].properties[13],
  );

  /// See [AttendanceEntity.isEdited].
  static final isEdited = obx.QueryBooleanProperty<AttendanceEntity>(
    _entities[0].properties[14],
  );

  /// See [AttendanceEntity.editedAt].
  static final editedAt = obx.QueryDateProperty<AttendanceEntity>(
    _entities[0].properties[15],
  );

  /// See [AttendanceEntity.expectedLunchStartMinute].
  static final expectedLunchStartMinute =
      obx.QueryIntegerProperty<AttendanceEntity>(_entities[0].properties[16]);
}

/// [WorkScheduleEntity] entity fields to define ObjectBox queries.
class WorkScheduleEntity_ {
  /// See [WorkScheduleEntity.id].
  static final id = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[0],
  );

  /// See [WorkScheduleEntity.startMinute].
  static final startMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[1],
  );

  /// See [WorkScheduleEntity.endMinute].
  static final endMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[2],
  );

  /// See [WorkScheduleEntity.lunchMinutes].
  static final lunchMinutes = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[3],
  );

  /// See [WorkScheduleEntity.reminderMinutes].
  static final reminderMinutes = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[4],
  );

  /// See [WorkScheduleEntity.workingDaysMask].
  static final workingDaysMask = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[5],
  );

  /// See [WorkScheduleEntity.lunchStartMinute].
  static final lunchStartMinute = obx.QueryIntegerProperty<WorkScheduleEntity>(
    _entities[1].properties[6],
  );
}

/// [LeaveReminderSettingsEntity] entity fields to define ObjectBox queries.
class LeaveReminderSettingsEntity_ {
  /// See [LeaveReminderSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[0],
  );

  /// See [LeaveReminderSettingsEntity.enabled].
  static final enabled = obx.QueryBooleanProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[1],
  );

  /// See [LeaveReminderSettingsEntity.homeLat].
  static final homeLat = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[2],
  );

  /// See [LeaveReminderSettingsEntity.homeLng].
  static final homeLng = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[3],
  );

  /// See [LeaveReminderSettingsEntity.workLat].
  static final workLat = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[4],
  );

  /// See [LeaveReminderSettingsEntity.workLng].
  static final workLng = obx.QueryDoubleProperty<LeaveReminderSettingsEntity>(
    _entities[2].properties[5],
  );

  /// See [LeaveReminderSettingsEntity.lastCommuteMinutes].
  static final lastCommuteMinutes =
      obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[6],
      );

  /// See [LeaveReminderSettingsEntity.lastCommuteUpdatedAt].
  static final lastCommuteUpdatedAt =
      obx.QueryDateProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[7],
      );

  /// See [LeaveReminderSettingsEntity.headsUpLeadMinutes].
  static final headsUpLeadMinutes =
      obx.QueryIntegerProperty<LeaveReminderSettingsEntity>(
        _entities[2].properties[8],
      );
}

/// [CheckoutReminderSettingsEntity] entity fields to define ObjectBox queries.
class CheckoutReminderSettingsEntity_ {
  /// See [CheckoutReminderSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<CheckoutReminderSettingsEntity>(
    _entities[3].properties[0],
  );

  /// See [CheckoutReminderSettingsEntity.enabled].
  static final enabled =
      obx.QueryBooleanProperty<CheckoutReminderSettingsEntity>(
        _entities[3].properties[1],
      );

  /// See [CheckoutReminderSettingsEntity.leadMinutes].
  static final leadMinutes =
      obx.QueryIntegerProperty<CheckoutReminderSettingsEntity>(
        _entities[3].properties[2],
      );
}
